export const TRACKERMENU = {
  workout: ["Chest", "Back", "Legs", "Shoulders", "Arms", "Abs", "Cardio"],
  type: [
    {
      name: "Free weights",
      options: ["Barbell", "Dumbbell", "Kettlebell", "Plates"],
    },
    {
      name: "Machine",
      options: [
        "Cable",
        "Smith",
        "Leg press",
        "Leg extension",
        "Lat pulldown",
        "Seated row",
        "Chest press",
        "Shoulder press",
        "Tricep extension",
      ],
    },
    {
      name: "Body weight",
      options: ["Pushups", "Pullups", "Dip", "Situp", "Crunch", "Plank"],
    },
    {
      name: "Cardio",
      options: [
        "Treadmill",
        "Elliptical",
        "Bike",
        "Stair climber",
        "Rowing machine",
        "Jump rope",
        "Swimming",
        "Hiking",
        "Running",
        "Walking",
        "Other",
      ],
    },
  ],
  sets: [0],
  reps: [0],
  weight: [0],
  distance: [0],
  time: [0],
  calories: [0],
  notes: [""],
};
